### ISSUE TITLE
Run Mazes.exe with an error return

### ISSUE THREAD

**Issue by Nazily215** [aPixelInSpace/F-a-maze-ing#7]
Dear author, your project is very interesting, and I want to try.
But I get an error when run your release bin file (Mazes.exe).

It returns "Unhandled exception. System.Exception: Number of verbs not supported
   at Program.main(String[] argv) in E:\Download\F-a-maze-ing-main\src\Mazes.CLI\Program.fs:line 248"

Any dependences I miss? Or I have to need something else before it can work on my computer?

Win10 Education Edition, VS2017, dotnet SDK 5.0.202

No matter what I build myself from source or download release exeecutable Mazes.exe, they would not work.

Thanks.

**Comment by aPixelInSpace** [comment]
Hi !

This error message is triggered when the number of arguments passed to the CLI is not correct.
Could you send me the command line (parameters/arguments) you use ?

It should be something like this : `.\Mazes.exe s-rectangle -r 6 -c 10 : g-ortho : a-hk -s 1 : rt-ortho -e : o-file -p "./test.txt"`

**Comment by Nazily215** [comment]
Many thanks. 
I only run cmd line "Mazes.exe" without any parameters to try if it works, so it return an error. I thought I will get some information back to show it ran normally, like version or author or website or something like that.
I try your suggestion, and it works (with some parameters).
Thank you.

The project is amazing, and is very funny. The solution is with animation, that's what I am be shocked most.
By the way, Mazes.exe will show a path (with a thin line or radian) solution instead of a filled cell solution?
If it can, what parameter should I tell him? Or will you consider to expand this path style to your project, if the program
does not have this function? (e.g. -s --solution-type line; -s --solution-type filled)

Thank you.

**Comment by aPixelInSpace** [comment]
I'm really happy that you like the project !

You're totally right, when running the CLI without any argument it should give a useful error message and not just some "dumb"  error :sweat_smile: 
I'll fix this in the next release.

As for rendering the solution path with a line instead of the whole cell, it is currently not possible but I'll add an option for it in the next release.

I'm currently in a rewrite of some large part of the code, to enable me to more easily add options and features in the future.

Thank you for your suggestions, I appreciate them.

**Comment by Nazily215** [comment]
Thanks for your answer and looking forward your next release.

**Comment by Nazily215** [comment]
I want to know if this project will be ran on Linux platform in the future ? (x86/64 or aarch64)

**Comment by aPixelInSpace** [comment]
The project uses the .Net Core platform which is compatible with Linux.
